### ISSUE TITLE
生成6.0的时候提示有重复键值，很多很多这个报错

### ISSUE THREAD

**Issue by slaners** [stratosblue/IntelliSenseLocalizer#5]
下面是报错内容
[13:34:14 W] Update IntelliSenseFile Group [system.windows.documents.floater.-ctor]
System.ArgumentException: An item with the same key has already been added. Key: childBlock
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at IntelliSenseLocalizer.MSDocPageAnalyser.CreatePageAnalysisResult(String uniqueKey, HtmlNode htmlNode) in D:\a\IntelliSenseLocalizer\IntelliSenseLocalizer\src\IntelliSenseLocalizer.Core\Utils\MSDocPageAnalyser.cs:line 79
   at IntelliSenseLocalizer.MSDocPageAnalyser.AnalysisHtmlDocument(HtmlDocument htmlDocument) in D:\a\IntelliSenseLocalizer\IntelliSenseLocalizer\src\IntelliSenseLocalizer.Core\Utils\MSDocPageAnalyser.cs:line 40
   at IntelliSenseLocalizer.MSDocIntelliSenseItemUpdater.UpdateAsync(IGrouping`2 intelliSenseItemGroup, CancellationToken cancellationToken) in D:\a\IntelliSenseLocalizer\IntelliSenseLocalizer\src\IntelliSenseLocalizer.Core\MSDocIntelliSenseItemUpdater.cs:line 48
   at IntelliSenseLocalizer.LocalizeIntelliSenseGenerator.<>c__DisplayClass4_0.<<GenerateAsync>b__1>d.MoveNext() in D:\a\IntelliSenseLocalizer\IntelliSenseLocalizer\src\IntelliSenseLocalizer.Core\LocalizeIntelliSenseGenerator.cs:line 81
![Clip_20230711_133503](https://github.com/stratosblue/IntelliSenseLocalizer/assets/49558888/ccb2e82b-0bf1-4d35-b55c-34a8a0ff24ff)

**Comment by stratosblue** [comment]
看起来可能是网页布局有变更，我抽时间看一下。。。

不过6.0的中文有现成的，没有特别的需求的话可以直接安装

```shell
islocalizer install auto -m net6.0 -cc OriginFirst
```

**Comment by slaners** [comment]
6.0.18这个小版本和最初的版本内容是一样的吗？我以为会不一样，所以想获取一下最新的数据

**Comment by stratosblue** [comment]
这种小版本都属于6.0，一般是安全更新，注释内容基本是不会变的，可以直接用

**Comment by slaners** [comment]
好的，懂了，谢谢
